apiVersion: v1
kind: Pod
metadata:
  name: codechecker-bot-pod
  namespace: default
  labels:
    app: codechecker-bot-pod
spec:
  containers:
  - name: codechecker-bot-container
    image: romilko/codechecker-bot:latest
    envFrom:
    - secretRef:
        name: bot-token
    ports:
    - containerPort: 8080
