apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command: ["/bin/bash", "-c"]
        args: ["minio server /data --console-address :8080"]
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: /data
            name: minio-data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-volume-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume
  labels:
    type: local
    app: minio
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-volume-claim
  labels:
    app: minio
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-api-node-port
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9000
      nodePort: 30005
---
apiVersion: v1
kind: Service
metadata:
  name: minio-ui-node-port
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
