apiVersion: v1
kind: Pod
metadata:
  name: minio
  labels:
    app: minio
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z-arm64
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30005
