apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:16
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_PASSWORD
      value: "postgres"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_DB
      value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 65432
